### ISSUE TITLE
Adding a category does not work on firefox(version 68.0.2) and edge 

### ISSUE THREAD

**Issue by extenditus** [gmazza/tightblog#1039]
This happened on a fresh install. I tried adding a category and nothing happened. I open the console on firefox and saw the below error.
`
TypeError: "obj.toElement is undefined"
    updateItem categories.js:49
    Angular 5
    jQuery 2`

On edge the error is 
`TypeError: Unable to get property 'dataset' of undefined or null reference
   at updateItem (https://localhost:8443/tb-ui/scripts/categories.js:49:9)
   at fn (Function code:2:244)
   at e (https://ajax.googleapis.com/ajax/libs/angularjs/1.7.0/angular.min.js:290:169)
   at m.prototype.$eval (https://ajax.googleapis.com/ajax/libs/angularjs/1.7.0/angular.min.js:151:503)
   at m.prototype.$apply (https://ajax.googleapis.com/ajax/libs/angularjs/1.7.0/angular.min.js:152:208)
   at Anonymous function (https://ajax.googleapis.com/ajax/libs/angularjs/1.7.0/angular.min.js:290:219)
   at n.event.dispatch (https://localhost:8443/tb-ui/scripts/jquery-2.2.3.min.js:3:7405)
   at r.handle (https://localhost:8443/tb-ui/scripts/jquery-2.2.3.min.js:3:5547)`

On chrome this works.

**Comment by extenditus** [comment]
Sorry - tightblog version 3.5.2

**Comment by gmazza** [comment]
Thanks for bringing this to my attention!  I normally use Chrome so didn't notice.  Bug turned up in three places, fixed in all in just-released 3.5.3.

**Comment by extenditus** [comment]
Hello Glen. Thanks for addressing this issue  quickly.
